- id: cadf
  type: puppet
  groups: [primary-controller, controller]
  required_for : [post_deployment_end]
  requires: [ceilometer-controller,openstack-controller,openstack-network,glance]
  parameters:
    puppet_manifest: "puppet/manifests/cadf.pp"
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720
